### PR TITLE
Allow using gh token

### PR DESCRIPTION
**Pull request by bhundven**

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution!

**Comment by suzuki-shunsuke** [comment]
Please don't do force push. 🙏

https://github.com/suzuki-shunsuke/oss-contribution-guide?tab=readme-ov-file#dont-do-force-pushes-after-opening-pull-requests

**Comment by bhundven** [comment]
Sorry, the branch was out of date, and I rebased with main.

**Comment by suzuki-shunsuke** [comment]
We have to update action.yaml too.

https://github.com/aquaproj/aqua-installer/blob/304d712082e06773b9e2920d4cd786e869bd066a/action.yaml#L52-L145

- https://github.com/aquaproj/aqua-installer/issues/461
- https://github.com/actions/runner/issues/2185

**Comment by suzuki-shunsuke** [comment]
> Sorry, the branch was out of date, and I rebased with main.

I see. Could you use merge instead of rebase from the next time?

**Comment by suzuki-shunsuke** [comment]
We download an asset from `https://github.com/aquaproj/aqua/releases/download/$bootstrap_version/$filename`.
We don't use GitHub REST API.
So I'm wondering Authorization header works fine.

I found some references that the Authorization header doesn't work in case of non REST API.

- https://github.com/orgs/community/discussions/47453
- https://stackoverflow.com/questions/20396329/how-to-download-github-release-from-private-repo-using-command-line

What do you think?

**Comment by suzuki-shunsuke** [comment]
> By allowing a github token to be used allows you to bypass the "API
rate limit" errors with github.com.

BTW, I'm not sure if GitHub API rate limiting occurs when we download assets from GitHub Releases without REST API.

**Comment by bhundven** [comment]
I tested locally with my own PAT for both curl and wget and that worked, with and without the PAT.

I just tested this a minute ago with my work dockerfile setup and this branch from GHES to github with a PAT, and it worked. Also got me past the rate limit issue.

I changed the `install-aqua.sh` to look like this:
```sh
#!/usr/bin/env bash

set -eu
set -o pipefail

CURL_OPTS=()
if [ -n "${AQUA_GITHUB_TOKEN}" ]; then
  CURL_OPTS+=("--header" "Authorization: Bearer ${AQUA_GITHUB_TOKEN}")
fi

curl "${CURL_OPTS[@]}" -sSfL https://raw.githubusercontent.com/bhundven/aqua-installer/allow_using_gh_token/aqua-installer | bash
```

based on this file (as I want install-aqua.sh to be updated by renovate in the future): https://github.com/aquaproj/test-aqua-renovate-config/blob/main/install-aqua.sh

**Comment by suzuki-shunsuke** [comment]
> BTW, I'm not sure if GitHub API rate limiting occurs when we download assets from GitHub Releases without REST API.

https://github.com/aquaproj/aqua/blob/adfd044dd03dc94e8fb59b0cdf972ef305ba6a9e/pkg/download/github_release.go#L33-L37

> I have tested if downloading assets from public repository's GitHub Releases anonymously is rate limited.
> As a result of test, it seems not to be limited.

**Comment by bhundven** [comment]
> > BTW, I'm not sure if GitHub API rate limiting occurs when we download assets from GitHub Releases without REST API.
> 
> https://github.com/aquaproj/aqua/blob/adfd044dd03dc94e8fb59b0cdf972ef305ba6a9e/pkg/download/github_release.go#L33-L37
> 
> > I have tested if downloading assets from public repository's GitHub Releases anonymously is rate limited.
> > As a result of test, it seems not to be limited.

This wasn't a problem with aqua updating applications, just with the aqua-installer.

**Comment by suzuki-shunsuke** [comment]
> This wasn't a problem with aqua updating applications, just with the aqua-installer.

Same with aqua-installer, aqua downloads assets from GitHub Releases.
So I looked into if the download from GitHub Releases without REST API caused API rate limiting before, and I concluded it didn't at that time.

**Comment by bhundven** [comment]
Error from my GHES runner workflow:
```
1.264 time="2024-03-07T23:33:29Z" level=fatal msg="aqua failed" aqua_version=2.22.0 env=linux/amd64 error="get the latest version of aqua: GET https://api.github.com/repos/aquaproj/aqua/releases/latest: 403 API rate limit exceeded for 40.64.111.205. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 7m10s]" program=aqua
```

**Comment by suzuki-shunsuke** [comment]
Did you face the rate limiting error when you download assets from GitHub Releases without REST API?
Then could you tell me the error message?

> I just tested this a minute ago with my work dockerfile setup and this branch from GHES to github with a PAT, and it worked.

If you faced any error without the authorization header and resolved the error with the authorization header,
it means the authorization header worked fine.
Did you confirm it?

**Comment by suzuki-shunsuke** [comment]
> Error from my GHES runner workflow before adding the header:
> 
> ```
> 1.264 time="2024-03-07T23:33:29Z" level=fatal msg="aqua failed" aqua_version=2.22.0 env=linux/amd64 error="get the latest version of aqua: GET https://api.github.com/repos/aquaproj/aqua/releases/latest: 403 API rate limit exceeded for 40.64.111.205. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 7m10s]" program=aqua
> ```

This is the error of aqua.
aqua-installer executes `aqua update-aqua` command internally.

https://github.com/aquaproj/aqua-installer/blob/304d712082e06773b9e2920d4cd786e869bd066a/aqua-installer#L97-L103

So to pass GitHub Access token to aqua, we don't have to update aqua-installer.

**Comment by bhundven** [comment]
Thank you!

**Pull request closed without merging**
