### PR TITLE
feat: add support for PowerShell

### PR DESCRIPTION
**Pull request by knqyf263**
Hi, thanks for the neat project. I'd like to use aquq with PowerShell on Windows. Looks like it currently supports bash only. This PR adds paths on PowerShell. Please correct me if I'm missing something as I'm not so familiar with Windows.

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Can we remove this?
https://github.com/aquaproj/aqua-installer/blob/b0e2539e93b49aeadfa703f77bee0dd326cef8e4/action.yaml#L33-L38

**Comment by knqyf263** [comment]
>Can we remove this?

It is needed for bash users.

>We have to use AQUA_ROOT_DIR if it is set.

I'll look into it.

**Comment by suzuki-shunsuke** [comment]
> It is needed for bash users.

Oh, really? I thought the following two steps do the same thing, but is it wrong? I'll take a look.

```yaml
- run: | 
     echo "$HOME/AppData/Local/aquaproj-aqua/bin" >> $GITHUB_PATH 
     echo "$HOME/AppData/Local/aquaproj-aqua/bat" >> $GITHUB_PATH 
  shell: bash 
  if: runner.os == 'Windows' 
  
- run: | 
    echo "$HOME/AppData/Local/aquaproj-aqua/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append 
    echo "$HOME/AppData/Local/aquaproj-aqua/bat" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append 
  shell: pwsh 
  if: runner.os == 'Windows' 
```

**Comment by knqyf263** [comment]
>Oh, really? I thought the following two steps do the same thing, but is it wrong? I'll take a look.

I also assumed it would work with either one, but it didn't work on PowerShell. Then, I eventually added both. I might be missing something as I'm not a Windows user...

I'm sorry to bother you. I'll use another branch for testing.
https://github.com/aquaproj/aqua-installer/actions/runs/3758036141/jobs/6385950789

**Comment by knqyf263** [comment]
Thanks for testing. I'll also give it another shot.

**Comment by suzuki-shunsuke** [comment]
BTW, this is an off topic but thank you for sharing your blog posts about Cosign such as [sigstoreによるコンテナイメージやソフトウェアの署名](https://knqyf263.hatenablog.com/entry/2022/02/06/213003).
Recently I'm interested in supply chain security and working on aqua's Cosign support.
Your blog posts are so helpful to understand Sigstore and Cosign.
I'd like to say thank you in this opportunity.

**Comment by knqyf263** [comment]
Could you take the following results? I might be doing something stupid.

## Without Out-File
Bash passes, while PowerShell fails.
Workflow: https://github.com/knqyf263/test-windows/actions/runs/3758355558/jobs/6386597971
File: https://github.com/knqyf263/test-windows/actions/runs/3758355558/workflow

## With Out-File
Bash and PowerShell both pass.
Workflow: https://github.com/knqyf263/test-windows/actions/runs/3758369635/jobs/6386630633
https://github.com/knqyf263/test-windows/actions/runs/3758369635/workflow

**Comment by knqyf263** [comment]
> BTW, this is an off topic but thank you for sharing your blog posts about Sigstore such as [sigstoreによるコンテナイメージやソフトウェアの署名](https://knqyf263.hatenablog.com/entry/2022/02/06/213003). Recently I'm interested in supply chain security and working on [aqua's Cosign support](https://github.com/aquaproj/aqua/issues/1452). Your blog posts are so helpful to understand Sigstore and Cosign. I'd like to say thank you in this opportunity.

I'm honored that you read my blog 😊

**Comment by suzuki-shunsuke** [comment]
Thank you for your investigation. It's interesting.
The difference of `PATH` is `C:\Users\runneradmin/AppData/Local/aquaproj-aqua/bin`.

```
C:\Users\runneradmin/AppData/Local/aquaproj-aqua/bin
/c/Users/runneradmin/AppData/Local/aquaproj-aqua/bat
/c/Users/runneradmin/AppData/Local/aquaproj-aqua/bin
```

Without `Out-File`, the path is unix style (the path separator is `/`) while with `out-file` the path is windows style(the path separator is `\`).

In windows, the default `shell` is pwsh.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

If we use `pwsh`, the unix style path doesn't work and windows style path is required.

**Comment by suzuki-shunsuke** [comment]
[6649f56](https://github.com/aquaproj/aqua-installer/pull/286/commits/6649f56ada5c3a5b078240bc35209a1fa4f3b2de) I've added tests with `pwsh`, and it has passed successfully.
It looks good.

**Comment by knqyf263** [comment]
Great catch! I didn't even imagine paths are converted. Thanks for figuring out it!

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/aquaproj/aqua-installer/releases/tag/v1.2.0

**Pull request merged**
